from config.paths import INCREMENTAL_FILE, INCREMENTAL_FOLDER
from src.utils.file_utils import create_incremental_file
from config.settings import INCREMENTAL_CONTENT

create_incremental_file(INCREMENTAL_CONTENT, INCREMENTAL_FILE, INCREMENTAL_FOLDER)